// Shared DeepSeek "curator pack" generator — reused by both the user-driven
// /api/curator-draft endpoint and the daily-curator scheduled function.
//
// The pack is produced in TWO separate DeepSeek calls instead of one:
//   1. core   — shortLabel + curatorNote + hotspots + questions + vocabulary
//   2. audio  — the three voice scripts (the bulky part)
// A single call that produced everything routinely blew past deepseek-chat's
// 8192-token output ceiling. When that happens json_object mode still returns
// *valid* JSON but silently closes the object early, dropping whatever came
// last — that's the "hotspots present, audio/questions/vocab empty" bug we hit
// on No.005 / No.006. Splitting means the small, must-have interactive content
// (questions, vocab, hotspots, note) is generated by a call that comfortably
// fits, and the audio scripts get their own full budget. If the audio call
// fails or truncates, the rest still ships — graceful degradation.

import { envVar } from './env.js';

export type CuratorPackInput = {
  title: string;
  artist: string;
  hint?: string;
  /** Optional factual grounding (e.g. a Wikipedia summary). Reduces the model's
   *  tendency to invent attributions — used by the roaming-landmark seeder. */
  context?: string;
};

export type Hotspot = { x: number; y: number; label: string; detail: string };
export type AudioLine = { t: number; text: string };
export type Question = { q: string; hint: string; options: string[] };
export type Vocab = { word: string; note: string; isNew: boolean };

export const VOICE_KEYS = ['清·克制', '专业·锐利', '诗意·散文'] as const;
export type VoiceKey = (typeof VOICE_KEYS)[number];

export type CuratorPack = {
  shortLabel: string;
  /** Personal-voice note shown next to the notebook. Per-work, not generic. */
  curatorNote: string;
  hotspots: Hotspot[];
  /** Three parallel script variants, keyed by narrator voice. */
  audioLines: Record<VoiceKey, AudioLine[]>;
  questions: Question[];
  vocabulary: Vocab[];
};

const STYLE_BASE = `你是"审美日课"的策展人助手。

风格基线（所有内容共通）：
- 中文衬线感、克制、不滥用形容词。
- 不卖弄学术，但术语用得准。
- 你的目标是**提高观众的审美、教他欣赏**，不是教他画画、讲技法课。永远站在"观众"这一侧：教他怎么看、看出门道、长出自己的判断；少讲"画家用了什么手法画出来的"。
- 永远把"它好在哪、妙在哪、为什么留得下来"讲清楚，落在观众能感知到的体会上，不要"我感觉它很好看"。`;

const CORE_SYSTEM_PROMPT = `${STYLE_BASE}

你将收到一件作品的标题、作者，以及一句话的感觉。返回**严格 JSON**，结构如下：

{
  "year": "年代（若背景资料里有，请据实填，如 \"1889\" 或 \"北宋\"；不确定就给空字符串，绝不编造）",
  "medium": "媒材（据实，如 \"布面油画\"/\"绢本设色\"/\"青铜\"/\"湿壁画\"；不确定给空字符串）",
  "location": "现藏地（据实，如 \"巴黎卢浮宫\"/\"北京故宫博物院\"；不确定给空字符串）",

  "shortLabel": "一句话墙签（25-40 字），讲清这幅作品在做什么、靠什么成立",

  "curatorNote": "策展人留言（60-100 字），第一人称、口语、像跟朋友说话。**必须针对当前这一幅作品**——抓住它的一个具体处理（构图/色彩/光/质感/视线/某个细节），给出'今晚做一件事'式的可复用动作。允许用引号、破折号。避免空泛的形容词。",

  "hotspots": [
    { "x": 0-100 数字, "y": 0-100 数字, "label": "看点名（4-7 字）", "detail": "看点说明（25-50 字）" }
  ],   // 必须正好 3 个

  "questions": [
    { "q": "问题（不超过 14 字）", "hint": "提示（25-35 字）", "options": ["选项一（4-8 字）", "选项二", "选项三", "选项四"] }
  ],   // 必须正好 3 题，依次：1) 第一眼，你被什么吸引？2) 它靠什么成立？3) 今天偷学一个动作？

  "vocabulary": [
    { "word": "词", "note": "释义（20-35 字）", "isNew": 布尔值 }
  ]    // 3-5 个该作品贡献的词
}

只输出 JSON，不要任何解释或 markdown 代码块标记。除 year/medium/location 三个事实字段允许在不确定时留空字符串外，其余字段都必须有内容，不允许留空数组。`;

// `lines` lets the retry ask for a SHORTER script — a long response is the main
// cause of truncation/timeout on the audio call, so the 2nd attempt degrades to
// fewer lines to fit more reliably.
const audioSystemPrompt = (lines: string, min: number) => `${STYLE_BASE}

你是一位陪观众站在画前看画的资深向导。请为这件作品写三档"欣赏导览"脚本，**目的是提高观众的审美、教他怎么欣赏这幅画**——不是教他画画、不是讲技法课。返回**严格 JSON**，结构如下：

{
  "audioLines": {
    "清·克制": [{ "t": 秒数, "text": "..." }, ...],
    "专业·锐利": [{ "t": 秒数, "text": "..." }, ...],
    "诗意·散文": [{ "t": 秒数, "text": "..." }, ...]
  }
}

立场（最重要，违反即失败）：
- 你在帮一位没有美术史背景的普通观众"看懂并爱上"这幅画、提高他的审美判断力。
- **讲"作为观众该怎么看、它好在哪、妙在哪、为什么动人、为什么经得起反复看"；不要讲"画家用了什么技法、是怎么画出来的、怎样运笔调色"**（除非某个做法直接关系到你眼睛能感受到的效果，且要落回"所以你看到/感到了什么"）。
- 每一句都站在观众这一侧。多说"你会注意到 / 你的眼睛会被带到 / 它之所以耐看，是因为"；少说"他用了 / 他通过……处理"。

内容走向（每档大致顺着这条线）：
- 先让眼睛停一停，说出第一眼最抓人的那个东西（先给感受，别急着解释）。
- 带观众真正看一两处值得停留的地方，说清"为什么这样就好看、就高级"——用能被眼睛感知的大白话，不要堆术语。
- 点出它为什么是好作品、为什么留得下来（落在观众的体会上，不是历史地位）。
- 最后一句，邀请观众写下自己的观察。

要求：
- 每一档 ${lines} 行，t 从 0 递增覆盖到约 ${min >= 8 ? 150 : 110} 秒。
- 三个 key 必须都出现，且每档都要有 ${min} 行以上，不允许留空。
- 三档讲同一组欣赏点，但语气节奏明显不同：
  · 清·克制：短句，留呼吸，每句 20-40 字，像一位安静的向导，只点不破。
  · 专业·锐利：判断果断、一针见血，每句 25-45 字，但说的是"为什么好看、为什么高级"，不是"怎么画的"。
  · 诗意·散文：句式更长，文白夹杂，允许偶有意象，每句 35-60 字，但始终指向真切的观看体验。

只输出 JSON，不要任何解释或 markdown 代码块标记。`;

function buildUserPrompt(input: CuratorPackInput) {
  const lines = [
    `作品名：${input.title || '（未填）'}`,
    `作者：${input.artist || '（未填）'}`,
    input.hint ? `一句话感觉：${input.hint}` : '没有额外感觉，请基于作品本身判断',
  ];
  if (input.context) {
    lines.push(
      `背景资料（仅供参考事实，请勿照抄，更不要编造资料里没有的人名/年代/归属）：\n${input.context}`,
    );
  }
  lines.push('请输出符合上述结构的 JSON。');
  return lines.join('\n');
}

/** One DeepSeek json_object call. Returns parsed object (typed by caller). */
async function callDeepSeek<T>(
  apiKey: string,
  systemPrompt: string,
  userPrompt: string,
  maxTokens: number,
): Promise<T> {
  const r = await fetch('https://api.deepseek.com/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: 'deepseek-chat',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.7,
      max_tokens: maxTokens,
      response_format: { type: 'json_object' },
    }),
  });

  if (!r.ok) {
    const text = await r.text();
    throw new Error(`DeepSeek 调用失败 (${r.status}): ${text.slice(0, 300)}`);
  }

  const data = (await r.json()) as {
    choices?: Array<{ message?: { content?: string }; finish_reason?: string }>;
  };
  const choice = data.choices?.[0];
  const content = choice?.message?.content;
  if (!content) throw new Error('DeepSeek 返回为空');
  // If the model hit the token ceiling, the JSON is truncated/closed early.
  if (choice?.finish_reason === 'length') {
    throw new Error('DeepSeek 输出被截断（达到 max_tokens）');
  }

  try {
    return JSON.parse(content) as T;
  } catch {
    throw new Error(`DeepSeek 返回的不是合法 JSON: ${content.slice(0, 300)}`);
  }
}

export type CorePack = Pick<
  CuratorPack,
  'shortLabel' | 'curatorNote' | 'hotspots' | 'questions' | 'vocabulary'
> & {
  /** Factual metadata the model fills from the grounding context (may be empty
   *  when no context is given or the fact is unknown). Used by the season
   *  pre-builder; daily-curator ignores these (it has its own seed metadata). */
  year?: string;
  medium?: string;
  location?: string;
};

/** Coerce / fill the three voice variants, falling back across them. */
function normalizeAudio(raw: unknown): Record<VoiceKey, AudioLine[]> {
  const out: Record<VoiceKey, AudioLine[]> = {
    '清·克制': [],
    '专业·锐利': [],
    '诗意·散文': [],
  };
  if (Array.isArray(raw)) {
    // Older / flattened shape — same script for all voices.
    for (const v of VOICE_KEYS) out[v] = raw as AudioLine[];
    return out;
  }
  const obj = (raw ?? {}) as Record<string, AudioLine[]>;
  for (const v of VOICE_KEYS) {
    if (Array.isArray(obj[v])) out[v] = obj[v];
  }
  // Fill any empty voice from the first non-empty one.
  const firstNonEmpty = VOICE_KEYS.map((v) => out[v]).find((a) => a.length) ?? [];
  for (const v of VOICE_KEYS) {
    if (!out[v].length) out[v] = firstNonEmpty;
  }
  return out;
}

function requireApiKey(): string {
  const apiKey = envVar('DEEPSEEK_API_KEY');
  if (!apiKey) throw new Error('DEEPSEEK_API_KEY 未配置');
  return apiKey;
}

/**
 * Generate the small, must-have interactive content (label + note + hotspots +
 * questions + vocabulary) in one DeepSeek call. Retries once if questions or
 * hotspots come back empty. Throws on total failure — this content is required.
 */
export async function generateCorePack(input: CuratorPackInput): Promise<CorePack> {
  const apiKey = requireApiKey();
  const userPrompt = buildUserPrompt(input);
  let lastErr: unknown = null;
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const c = await callDeepSeek<CorePack>(apiKey, CORE_SYSTEM_PROMPT, userPrompt, 4096);
      if (c.questions?.length && c.hotspots?.length) return c;
      lastErr = new Error('核心包字段为空（questions/hotspots）');
    } catch (e) {
      lastErr = e;
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error(String(lastErr));
}

/**
 * Generate the three voice scripts in a dedicated call (the bulky part).
 * Best-effort: retries once on truncation/empty, then returns empty arrays
 * rather than throwing — callers treat missing audio as non-fatal.
 */
export async function generateAudioScripts(
  input: CuratorPackInput,
): Promise<Record<VoiceKey, AudioLine[]>> {
  const apiKey = requireApiKey();
  const userPrompt = buildUserPrompt(input);
  // Attempt 0: full script. Attempt 1: shorter script (fewer lines) so a
  // truncation/timeout on the heavy first try degrades to something that fits.
  const variants = [
    { sys: audioSystemPrompt('8-12', 8), tok: 8192 },
    { sys: audioSystemPrompt('6-8', 6), tok: 8192 },
  ];
  for (const v of variants) {
    try {
      const a = await callDeepSeek<{ audioLines?: unknown }>(apiKey, v.sys, userPrompt, v.tok);
      const normalized = normalizeAudio(a.audioLines);
      if (VOICE_KEYS.some((k) => normalized[k].length)) return normalized;
    } catch {
      // swallow — try the lighter variant, then give up gracefully
    }
  }
  return normalizeAudio(null);
}

/**
 * Convenience: full pack via two DeepSeek calls (core + audio). Used by the
 * user-driven /api/curator-draft. The daily cron calls the two functions
 * separately so it can persist the core content before attempting audio.
 */
export async function generateCuratorPack(input: CuratorPackInput): Promise<CuratorPack> {
  const core = await generateCorePack(input);
  const audioLines = await generateAudioScripts(input);
  return {
    shortLabel: core.shortLabel,
    curatorNote: core.curatorNote,
    hotspots: core.hotspots ?? [],
    questions: core.questions ?? [],
    vocabulary: core.vocabulary ?? [],
    audioLines,
  };
}
