// Curated seed list for the daily auto-publish cron.
// Each entry has enough metadata that DeepSeek can write a curator pack with
// real content (not hallucinated). The `wikipediaSlug` + `wikipediaLang` pair
// is used at runtime to fetch a public-domain image via the Wikipedia REST API
// (no hardcoded image URLs — those are fragile when Wikimedia moves files).
//
// Order matters: the cron picks seed[count % SEED_WORKS.length], so the
// sequence is deterministic. Add new works to the END of the list to avoid
// disrupting the rotation for existing days.

export type SeedWork = {
  /** Wikipedia article slug (with underscores). */
  wikipediaSlug: string;
  /** Wikipedia language code to query. */
  wikipediaLang: 'zh' | 'en' | 'ja';
  title: string;
  artist: string;
  artistRomaji: string;
  year: string;
  medium: string;
  size: string;
  series?: string;
  location: string;
  /** One-line prompt seed passed to DeepSeek along with title/artist. */
  hint: string;
};

export const SEED_WORKS: SeedWork[] = [
  {
    wikipediaSlug: 'Fine_Wind,_Clear_Morning',
    wikipediaLang: 'en',
    title: '凯风快晴',
    artist: '葛饰北斋',
    artistRomaji: 'Katsushika Hokusai',
    year: '约 1830–1832',
    medium: '木版画 · 锦绘',
    size: '25.5 × 38.0 cm',
    series: '《富岳三十六景》',
    location: '现存大英博物馆等',
    hint: '夏末清晨的几分钟里富士山被南风染成赤铜色——北斋用最少元素捕获了一次"气象"',
  },
  {
    wikipediaSlug: 'Mona_Lisa',
    wikipediaLang: 'en',
    title: '蒙娜丽莎',
    artist: '列奥纳多·达·芬奇',
    artistRomaji: 'Leonardo da Vinci',
    year: '约 1503–1519',
    medium: '木板油画',
    size: '77 × 53 cm',
    location: '卢浮宫',
    hint: '微笑里的不确定性来自 sfumato（晕涂法）——边缘没有线，只有光气',
  },
  {
    wikipediaSlug: 'The_Starry_Night',
    wikipediaLang: 'en',
    title: '星夜',
    artist: '文森特·梵高',
    artistRomaji: 'Vincent van Gogh',
    year: '1889',
    medium: '布面油画',
    size: '73.7 × 92.1 cm',
    location: '纽约现代艺术博物馆',
    hint: '夜空被画成一个动力学系统——卷云像漩涡，星像漩涡的核',
  },
  {
    wikipediaSlug: 'The_Great_Wave_off_Kanagawa',
    wikipediaLang: 'en',
    title: '神奈川冲浪里',
    artist: '葛饰北斋',
    artistRomaji: 'Katsushika Hokusai',
    year: '约 1831',
    medium: '木版画 · 锦绘',
    size: '25.7 × 37.8 cm',
    series: '《富岳三十六景》',
    location: '大英博物馆等',
    hint: '前景的巨浪被放大到几乎吞掉富士——尺度是被故意搞错的',
  },
  {
    wikipediaSlug: 'Girl_with_a_Pearl_Earring',
    wikipediaLang: 'en',
    title: '戴珍珠耳环的少女',
    artist: '约翰内斯·维米尔',
    artistRomaji: 'Johannes Vermeer',
    year: '约 1665',
    medium: '布面油画',
    size: '44.5 × 39 cm',
    location: '海牙莫瑞泰斯皇家美术馆',
    hint: '一个回眸的瞬间——头巾的群青和耳环的高光是画面里仅有的"亮"',
  },
  {
    wikipediaSlug: 'The_Scream',
    wikipediaLang: 'en',
    title: '呐喊',
    artist: '爱德华·蒙克',
    artistRomaji: 'Edvard Munch',
    year: '1893',
    medium: '蛋彩、蜡笔、纸板',
    size: '91 × 73.5 cm',
    location: '奥斯陆国家美术馆',
    hint: '不是人在喊，是天空和大地在喊，人物被它们裹挟',
  },
  {
    wikipediaSlug: 'Liberty_Leading_the_People',
    wikipediaLang: 'en',
    title: '自由引导人民',
    artist: '欧仁·德拉克罗瓦',
    artistRomaji: 'Eugène Delacroix',
    year: '1830',
    medium: '布面油画',
    size: '260 × 325 cm',
    location: '卢浮宫',
    hint: '画里同时存在写实人物和神话女神——这种"调换比例"是浪漫主义的发明',
  },
  {
    wikipediaSlug: 'The_Birth_of_Venus',
    wikipediaLang: 'en',
    title: '维纳斯的诞生',
    artist: '桑德罗·波提切利',
    artistRomaji: 'Sandro Botticelli',
    year: '约 1485',
    medium: '布面蛋彩',
    size: '172.5 × 278.9 cm',
    location: '佛罗伦萨乌菲兹美术馆',
    hint: '人物像从浮雕里走出来——线条比体积重要',
  },
  {
    wikipediaSlug: 'The_School_of_Athens',
    wikipediaLang: 'en',
    title: '雅典学院',
    artist: '拉斐尔',
    artistRomaji: 'Raphael',
    year: '1509–1511',
    medium: '湿壁画',
    size: '500 × 770 cm',
    location: '梵蒂冈使徒宫',
    hint: '透视把所有人都引向中心两位——柏拉图与亚里士多德',
  },
  {
    wikipediaSlug: 'The_Night_Watch',
    wikipediaLang: 'en',
    title: '夜巡',
    artist: '伦勃朗',
    artistRomaji: 'Rembrandt van Rijn',
    year: '1642',
    medium: '布面油画',
    size: '363 × 437 cm',
    location: '阿姆斯特丹国立博物馆',
    hint: '集体肖像被处理成戏剧场景——光不是均匀的，是聚光的',
  },
  {
    wikipediaSlug: 'Impression,_Sunrise',
    wikipediaLang: 'en',
    title: '印象 · 日出',
    artist: '克劳德·莫奈',
    artistRomaji: 'Claude Monet',
    year: '1872',
    medium: '布面油画',
    size: '48 × 63 cm',
    location: '巴黎玛摩丹美术馆',
    hint: '橙色的太阳和灰蓝的港口——明度几乎相同，黑白复印就消失了',
  },
  {
    wikipediaSlug: 'A_Sunday_on_La_Grande_Jatte',
    wikipediaLang: 'en',
    title: '大碗岛的星期日下午',
    artist: '乔治·修拉',
    artistRomaji: 'Georges Seurat',
    year: '1884–1886',
    medium: '布面油画',
    size: '207.5 × 308.1 cm',
    location: '芝加哥艺术博物馆',
    hint: '颜色不是混在调色板上，是混在眼睛里——这是科学方法',
  },
  {
    wikipediaSlug: 'The_Persistence_of_Memory',
    wikipediaLang: 'en',
    title: '记忆的永恒',
    artist: '萨尔瓦多·达利',
    artistRomaji: 'Salvador Dalí',
    year: '1931',
    medium: '布面油画',
    size: '24.1 × 33 cm',
    location: '纽约现代艺术博物馆',
    hint: '只有时间是软的——其它一切：地平线、岩石、桌子，都被画得很硬',
  },
  {
    wikipediaSlug: 'Guernica_(Picasso)',
    wikipediaLang: 'en',
    title: '格尔尼卡',
    artist: '巴勃罗·毕加索',
    artistRomaji: 'Pablo Picasso',
    year: '1937',
    medium: '布面油画',
    size: '349.3 × 776.6 cm',
    location: '马德里索菲娅王后博物馆',
    hint: '只有黑白灰——彩色会让灾难变好看',
  },
  {
    wikipediaSlug: 'Nighthawks',
    wikipediaLang: 'en',
    title: '夜游者',
    artist: '爱德华·霍珀',
    artistRomaji: 'Edward Hopper',
    year: '1942',
    medium: '布面油画',
    size: '84.1 × 152.4 cm',
    location: '芝加哥艺术博物馆',
    hint: '没有人在交谈——四个人，四种孤独，被荧光灯照亮',
  },
  {
    wikipediaSlug: 'Composition_with_Red,_Blue_and_Yellow',
    wikipediaLang: 'en',
    title: '红黄蓝构成',
    artist: '皮特·蒙德里安',
    artistRomaji: 'Piet Mondrian',
    year: '1930',
    medium: '布面油画',
    size: '46 × 46 cm',
    location: '苏黎世美术馆',
    hint: '只有三原色和黑色——但色块大小不等，画面就有了节奏',
  },
  {
    wikipediaSlug: 'American_Gothic',
    wikipediaLang: 'en',
    title: '美国哥特式',
    artist: '格兰特·伍德',
    artistRomaji: 'Grant Wood',
    year: '1930',
    medium: '画板油画',
    size: '78 × 65.3 cm',
    location: '芝加哥艺术博物馆',
    hint: '叉子的三齿和窗框的尖拱——画面里所有"垂直"在互相回应',
  },
  {
    wikipediaSlug: 'Water_Lilies_(Monet_series)',
    wikipediaLang: 'en',
    title: '睡莲',
    artist: '克劳德·莫奈',
    artistRomaji: 'Claude Monet',
    year: '1899–1926',
    medium: '布面油画',
    size: '尺寸不一',
    series: '《睡莲》系列',
    location: '巴黎橘园美术馆等',
    hint: '没有天空也没有岸——观者悬在水面之上',
  },
  {
    wikipediaSlug: 'The_Basket_of_Apples',
    wikipediaLang: 'en',
    title: '苹果篮子',
    artist: '保罗·塞尚',
    artistRomaji: 'Paul Cézanne',
    year: '约 1893',
    medium: '布面油画',
    size: '65 × 80 cm',
    location: '芝加哥艺术博物馆',
    hint: '桌沿不在一条线上——塞尚有意把视点错位，让平面有体积',
  },
  {
    wikipediaSlug: 'Sunflowers_(Van_Gogh_series)',
    wikipediaLang: 'en',
    title: '向日葵',
    artist: '文森特·梵高',
    artistRomaji: 'Vincent van Gogh',
    year: '1888',
    medium: '布面油画',
    size: '92.1 × 73 cm',
    series: '《向日葵》系列',
    location: '伦敦国家美术馆等',
    hint: '黄色压满整个画面——梵高用单一色相做整张画',
  },
  {
    wikipediaSlug: '富春山居图',
    wikipediaLang: 'zh',
    title: '富春山居图',
    artist: '黄公望',
    artistRomaji: 'Huang Gongwang',
    year: '1350',
    medium: '纸本水墨',
    size: '33 × 636.9 cm（合卷）',
    location: '台北故宫博物院 · 浙江省博物馆（分藏）',
    hint: '一卷展开三百年的退隐——皴法极简，山水里几乎没人',
  },
  {
    wikipediaSlug: '千里江山图',
    wikipediaLang: 'zh',
    title: '千里江山图',
    artist: '王希孟',
    artistRomaji: 'Wang Ximeng',
    year: '约 1113',
    medium: '绢本设色',
    size: '51.5 × 1191.5 cm',
    location: '北京故宫博物院',
    hint: '十八岁画青绿山水——天才的画里没有犹豫',
  },
  {
    wikipediaSlug: '清明上河图',
    wikipediaLang: 'zh',
    title: '清明上河图',
    artist: '张择端',
    artistRomaji: 'Zhang Zeduan',
    year: '约 1100',
    medium: '绢本水墨淡设色',
    size: '24.8 × 528 cm',
    location: '北京故宫博物院',
    hint: '一卷里五百多人——每个人都在做自己的事，没有"主角"',
  },
  {
    wikipediaSlug: '韩熙载夜宴图',
    wikipediaLang: 'zh',
    title: '韩熙载夜宴图',
    artist: '顾闳中',
    artistRomaji: 'Gu Hongzhong',
    year: '约 970',
    medium: '绢本设色',
    size: '28.7 × 335.5 cm',
    location: '北京故宫博物院',
    hint: '同一个人在五幕里出现——这是中国画里少见的"分镜"',
  },
  {
    wikipediaSlug: '簪花仕女图',
    wikipediaLang: 'zh',
    title: '簪花仕女图',
    artist: '周昉',
    artistRomaji: 'Zhou Fang',
    year: '约 8 世纪末',
    medium: '绢本设色',
    size: '46 × 180 cm',
    location: '辽宁省博物馆',
    hint: '唐人的丰腴是体积感——人物像被风吹起来的纨扇',
  },
  {
    wikipediaSlug: '五牛图',
    wikipediaLang: 'zh',
    title: '五牛图',
    artist: '韩滉',
    artistRomaji: 'Han Huang',
    year: '约 8 世纪',
    medium: '黄麻纸本设色',
    size: '20.8 × 139.8 cm',
    location: '北京故宫博物院',
    hint: '五头牛朝向不同——动物画里少有的"群像"',
  },
  {
    wikipediaSlug: '步辇图',
    wikipediaLang: 'zh',
    title: '步辇图',
    artist: '阎立本',
    artistRomaji: 'Yan Liben',
    year: '约 641',
    medium: '绢本设色',
    size: '38.5 × 129 cm',
    location: '北京故宫博物院',
    hint: '画的是接见——但画面重心被故意压在唐太宗一侧',
  },
  {
    wikipediaSlug: '洛神赋图',
    wikipediaLang: 'zh',
    title: '洛神赋图',
    artist: '顾恺之（传）',
    artistRomaji: 'Gu Kaizhi (attrib.)',
    year: '约 4 世纪（宋摹本）',
    medium: '绢本设色',
    size: '27.1 × 572.8 cm',
    location: '北京故宫博物院 · 辽宁省博物馆等',
    hint: '同一个洛神在一卷里反复出现——文字的"赋"被画成了空间',
  },
  {
    wikipediaSlug: 'The_Treachery_of_Images',
    wikipediaLang: 'en',
    title: '形象的叛逆（这不是一只烟斗）',
    artist: '勒内·马格利特',
    artistRomaji: 'René Magritte',
    year: '1929',
    medium: '布面油画',
    size: '63.5 × 93.98 cm',
    location: '洛杉矶郡艺术博物馆',
    hint: '画和文字在打架——这是一只烟斗的画，不是一只烟斗',
  },
  {
    wikipediaSlug: 'Las_Meninas',
    wikipediaLang: 'en',
    title: '宫娥',
    artist: '迭戈·委拉斯开兹',
    artistRomaji: 'Diego Velázquez',
    year: '1656',
    medium: '布面油画',
    size: '318 × 276 cm',
    location: '马德里普拉多博物馆',
    hint: '画家把自己画进画里——观众站在国王和王后被画的位置上',
  },
];
